py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9
  script:
  - pip install tox
  - tox -e py39

py310:
  image: python:3.10
  script:
  - pip install tox
  - tox -e docs,format,mypy,package,pep8,py310

pages:
  image: python:3.10
  script:
  - pip install Sphinx pydata-sphinx-theme .
  - rm -rf docs/source
  - sphinx-apidoc -e -f -o docs/reference/source/ src/quart/
  - sphinx-build -b html docs/ docs/_build/html/
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
